---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.50.50.200-10.50.50.250
  INGRESS_NGINX_LB: 10.50.50.240
  LB_TRAEFIK_IP: 10.50.50.200