---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    master-nodes:
      hosts:
        apnas01:
        apk8s00:
        aprp01:
    # Node group, do not change the 'node' name
    # hosts should match the filenames in 'host_vars'
    worker-nodes:
      hosts:
        apk8s01:
        apk8s02:
        aprp02:
        aprp03:
        aprp04:
        aprp05:
        aprp06:
        aprp07:
        aprp08:
        aprp09:
        aprp10:
        aprp11:
        aprp12:
        aprp13:
        aprp14:
        aprp15:
        aprp16:
        aprp17:
        aprp18:
        aprp19:
 