---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  GATEWAY_IP: 10.50.50.1
  NETWORK_K8S_CLUSTER_CIDR: 10.150.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.250.0.0/16
  METALLB_LB_RANGE: 10.50.50.200-10.50.50.250
  INGRESS_NGINX_LB: 10.50.50.240
  LB_TRAEFIK_IP: 10.50.50.200
  LB_COREDNS_IP: 10.50.50.220
  LB_LOKI_IP: 10.50.50.221
  LB_PLEX_IP: 10.50.50.222
  LB_JELLYFIN_IP: 10.50.50.223
  LB_BLOCKY_IP: 10.50.50.224
  LB_QBITTORRENT_IP: 10.50.50.225
  LB_OWNCAST_IP: 10.50.50.226
