# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: prodromou.com
    SECRET_CLOUDFLARE_EMAIL: nate@prodromou.com
