# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:37SEwJLzBSYB4mAWtA==,iv:5qwox26qdVqts0xe0j4FwzXfOX4Fxw7onohG1cn1Lgo=,tag:WS6el6yLfI269Ci5LIGUng==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2+n9t7MydzTyAPZYyxrcXBo4,iv:V8mc9ih4/ZCBx26LsF9PsfAAN/5pfB+HBYsTOd+Qxzc=,tag:O0EfK9/f4bUkxk/IIhS7/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-04T23:44:33Z"
    mac: ENC[AES256_GCM,data:aFK47bykjCaDxoNMKlMRomVCwOjSzDOBFqGMVY1bJoUuw5HQZC8tesLgSfccffz54OoexlvsbvBAvHOaRk6NufKDrjzpndOOZAk1V1wZjMJioW+CnrWfTpOURogZyi1Db7RwfGzWCQGWvvKMd4Th46IY2wCTZwpJZiwneKcv48E=,iv:jN0zDd2dPm0g4AGltuYA8zO5JkfWoFLjuOhti+Rf9Wc=,tag:v8FESYcv2g+TrYklvQgYHQ==,type:str]
    pgp:
        - created_at: "2021-10-04T23:44:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+3OAxXx2YMsARAAkrhiSEroH3nEm7nndJKbVrzi3MBKWJOIzX+gLftnzMIY
            P5g5PPYYJBGw8VsDdDcVTVVP/bSUwF+wDSh5rjHrzz+Jrwi2kTvhe3Q6mnxVuG62
            E/urxfATks+i5bDkoFS/weIFg6xSWypbvaUjOnW2JvjaY9zu1TUNd9I34HZ8jG1t
            xjaaD7NZPmgPyUj+0m1Sct7hjE7L+xTPef8iFIQFheuNUrPgq23JqPdeGHwsM4oK
            gwKfga5tREkXINhQ6u09c3QieY8zxd//du2pYfF6tTSeXio4bc7k/GRDDgjbCbhb
            2dXqy+ardFU3wBp7EiMLUuvFzz5VBKwIOW+K5PEpXQX0bXuAaRcDMBJbAB3/BT4B
            ilR1zbolV/j9eedhQnHGhT1XLJvw6yRahVT405p3U2gSbShqxxTBzoA/hTDoY24C
            SClam1mhXb1plZ2QMpDC1gRp47V788321F1gnMaoXx3K3whbiNfHLaJGaqtwo6Jk
            5vafP2FMdIWHLBZj4cIlQlOYRA8Oc/1dHz3ZsD0G/aItyfI5YDjlcTzn56mhAjn0
            5WJFSCkLXk/q2mn6y5QJCdmlT/V8gcpBgDXb0iBcAdrYQ4OeDPvD+7y7SOofclLA
            w1kF71pomf4Q0BAAGhwa16puLpsi4nhhLdB7HyKlyYmMmGDSoDk1ZscS+PlX2EzS
            XgEOzZ6z8KHxfDaYo+IVurpisA9t5iZlqtpHR4Dicucj2ZKMd+SGXYt9HVebDXLE
            bXQPCc3r7jLU0RAL/eg2497nfCkO1i9X51wfztP4Zpzd6vDJcXGxEy9DY85YRj8=
            =cvck
            -----END PGP MESSAGE-----
          fp: C84A5994F24D54C0BEAA413BEDCE0315F1D9832C
        - created_at: "2021-10-04T23:44:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzqFzAzDaaggAQ/+OP5wruz+xWP186xwJm0MJZLagx9ea/32gCIHhefnQ66x
            GyQrKubHf5FvtZSb2dbPkGNeusKrCrQnzF8xPQPUea9uIi/SukU5+3D1BWoSt/HU
            vm9S3clTvsZ3YBiq75fDuiraOlMNHGQ5jelEmxWdLofcS9VJJbQXj1MFyw1NMtCG
            rO/0HdZLgWjpyxKzVCD0gtlBwfq+v8ZyB14WIAQ/1QKtsDitGKo6glLIy7CKnKhw
            aBSFDNAgxNhbmP5tHpsBBLylzxocxJHzLZHkETymPcztyd8kqGTpCZ2k4d2Rk1RW
            +p8g2e9s8xSzSrlW4lupfaGnnazjpbj8iKAvD5oqRH2DHVlllG+BLRjKajtZFZgP
            kHO0R8Hdx9hcOXwIzbLIBtnaTUMHSJb+iLJ1XCoCruQPzUkQfLJE4RcPeXCUwkCZ
            2OP6nb+Z1C4YkIYhjLxeFecx5Hh0IcmUJ3eEpyg8lBmmLyFW7Vd9ocLqJ67u82d5
            vMQ8SefFQhLdJbmVUMxxG803ZLj37tftFVVHSM3XquN6kSxQ2Kwy1dgk73W9NhFR
            IBSs2Q/CmYtNyAJkyU5bA9l9xOI1VbNdn8uvy1gGc3Jn36UkF0ILUfSxG1TbVMMZ
            ENENaV8etNPnHYoZjpOr6sZ1a+vIsWlJWhn5+hPj5FvjouL/2qnZUZzTosCK8V3S
            XgHC3ZBIG6BpTXq9w9DX062cDLjZaOd0EJF6ifXKUzGtQGLr6D7JeOEt6riCdD2q
            yRQCaXcgDNVViskjlOX91nW3lE4iZdMc61Vn6Y6h7zOrBe/y0rgewfjd225441Q=
            =zL9H
            -----END PGP MESSAGE-----
          fp: 6224417B1B04CC0BC8F7A7983A85CC0CC369A820
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
