# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nOrUjmSq5dGxoo8dWQ==,iv:uYDGu7YoSI9My9sTMJT5hdN2TCVaLm4bdrHxh4gCcJw=,tag:1RDzz1QHbXccHPPdC34G3A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tuoqgjNfqa+Pgf3dgdR8g2qI,iv:zxs6z7gFz5hiRM4ohfkExaCBXHxpdO7LBmCS4F6se9c=,tag:6xBvHzPEhs+mjwpBo1OS/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-06T15:54:26Z"
    mac: ENC[AES256_GCM,data:2erlEPaJiaNksDyCoSlEKn2Gf3LCVe+fMuTguexigwuSERdwIMJT+wTtqEFEW/gc17/IUJdGjg7J1bNaQTdmlRDf0049F+AWQbE7Qgt7DhqW5+21Es3ICBkUAG9bsjK+57rzC7TcHQ1PEZ3QaSvFBWvmS4ssnwKTZ7ML4m7b9q8=,iv:8p5rOOt0aHM2gSjKJNNnvOYYtZYHmhYgAW2kBuH2oP8=,tag:HmUxL/JQfIamO/hR5G7hUA==,type:str]
    pgp:
        - created_at: "2021-10-06T15:54:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2yEuocBWDw7AQ//Qj8ku0flVdoT3cSo4p5Owto+m4ATFmtRZL9bmCgIt2+E
            6DpVNpHGP0Aq1ZROsY1tFBFdpRLB/DW97DAeUhxif5/yT5Hden6vQqA84irAJUEA
            1e9kyxpGQhgJ8BQAA2CHJjvnrO7XwP9dj5WEL0MQz8vNonzNrV299OTrTl8xBXH0
            BCz4auUirXkIFYDw6RqCYl2N1LLyGIv1kGtn0iMhWheksnI6i4eCmyxGEg9Sh7IA
            F+bNjRq5kA3b3cRjslDrbFYSgXzZXtavzxzzT1Bqc3tCU9PxKEB7NHYPSDa6wcjf
            FfdGmcCy+vCDc71unnZ1JJAABFUlW7DbStIHZWjyvcuDx4LVtEpfq2rV/QstRk9m
            Ok2AskQIBvtdNb5vx4PQREyM1ehYJ4zz9xBptVfVJfCU3icllKksA5IWJF3FaWid
            CG3JqJvNWDB/2vBthT9CcE/rcoeS8O1ZdPI8ED0+DI1IY8kzOO3CQzuXAQA90JY5
            1JQPhhKF1L8KrGZzZDyBO1xrXWhXduRlnPKrQ1DzM8fBPiIpKpn4J7YjNb1TDTJL
            u0ow9VBq21zjeXqcbEFI/y8ZNMB2VK0B7x2+KdLxWMEM0xE/NMjEyO6A1oKWT5v/
            f8nWJfHB53O7sxQ6JNnsiNvMqMm32XC+iQ8GpMd4buq6y6akIDyDc6U4Tm5s05fS
            XgEtkGJFZ1Xuu9sGyeO0yCnVxXst+rVHNe6WWNE4k3XY47z6txAmh5Bkb7j2gn7U
            c0PbWlVMl7T7w2xAU6Ursg+5/amj10rLCYRkyUIIKkIqyaJVMLXIQ4wahxDwyJs=
            =s6Qj
            -----END PGP MESSAGE-----
          fp: 448F24663C24E0FE39C730756C84BA8701583C3B
        - created_at: "2021-10-06T15:54:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzqFzAzDaaggAQ//WHiLSjiGz7MxCp9hmw1ItD2voeYTbEs2Su3voDLzbVGn
            mV7kcmHsl3VG99opPOtYh+RWEcpV4RNSmoSJrSwpFPLpFAdqGPaodqMbY+0CMg4R
            i6D6wJY2v9QkIlsEg9oLK0B4QMa8XITTvyr6/uuLALokT+wMiMF2L6NuHl9j3y/A
            oLm1IsZ0RtUls7X3H9HuE+h8qv87iVaO5rCbaGh0qiMmH/KOGUVJqEIHKdLB4jrD
            gdG56dZAn5ZjNZuM88trfmVexqIZ5H3x4rsvoOk6Z9dP7bnKDKEKvWI8XiLXHKsc
            nRRbpCMrd7qhW79f9/k9puxs8/bJ++YKyO6eZmdP3s0OdYYyQkndEeihRBmmP/Dh
            1CLNY9bj4rvsoW/WmTXefMU4d8pkTM7BVd8ITPHmc81ndrspiXJKqbCPsPFQVVRu
            iV/vRdz+z8jS5+iflH3SiOgHL+VajjZrEZ7B2xvCFJmrnHg6tGoyzZC5CYZxPbVR
            wrrSsDOdP3k+Z7YDXBJTtXEB9y5qC+dtu+RQDYEW4+rZLkdvUZA8PHqwDBZS5b3w
            lTvoubbuIzQ0mNVAikPrvdLS6IzxZCn4XjSPoIJAON2mOVOirRjy1spjtWgp4drH
            ObcQOk1+UJcJUdC3R+C/BSrFWfjViMDjWj6aeN8nBjBC/m8dd4qpSniQnOrEJYbS
            XgH3n1x1E4JaO2NanBENC8PzaQjHR56od059m/CMhOAYkEtM4VNmuKBKtlN1JfiO
            gj2e7Q3RXzx0z/9WNXZT30zIcfe25JocTzXysKrjrfPtJBru7EYnovAh2qTsrTA=
            =nZW7
            -----END PGP MESSAGE-----
          fp: 6224417B1B04CC0BC8F7A7983A85CC0CC369A820
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
