---

- include: locale.yml
  tags:
  - locale

- include: packages.yml
  tags:
  - packages

- include: kernel.yml
  tags:
  - kernel

- include: monit.yml
  tags:
  - monit

- include: filesystem.yml
  tags:
  - filesystem

- include: unattended-upgrades.yml
  tags:
  - unattended-upgrades

- include: user.yml
  tags:
  - user
