---

kubernetes:
  children:
    master:
      hosts:
        apk3s00:
          ansible_host: 10.50.50.30
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: true
        apk3s01:
          ansible_host: 10.50.50.31
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: true
        apk3s02:
          ansible_host: 10.50.50.32
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: true
      vars:
        ansible_user: nprodromou
        
    worker:
      hosts:
        apk8s00:
          ansible_host: 10.50.50.40
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        apk8s01:
          ansible_host: 10.50.50.41
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        apk8s02:
          ansible_host: 10.50.50.42
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        apnas01:
          ansible_host: 10.50.50.10
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp01:
          ansible_host: 10.50.50.101
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp02:
          ansible_host: 10.50.50.102
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp03:
          ansible_host: 10.50.50.103
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp04:
          ansible_host: 10.50.50.104
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp05:
          ansible_host: 10.50.50.105
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp06:
          ansible_host: 10.50.50.106
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp07:
          ansible_host: 10.50.50.107
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp08:
          ansible_host: 10.50.50.108
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp09:
          ansible_host: 10.50.50.109
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp10:
          ansible_host: 10.50.50.110
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp11:
          ansible_host: 10.50.50.111
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp12:
          ansible_host: 10.50.50.112
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
          rook_devices:
          - /dev/sda1
        aprp13:
          ansible_host: 10.50.50.113
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp14:
          ansible_host: 10.50.50.114
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp15:
          ansible_host: 10.50.50.115
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp16:
          ansible_host: 10.50.50.116
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp17:
          ansible_host: 10.50.50.117
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp18:
          ansible_host: 10.50.50.118
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false
        aprp19:
          ansible_host: 10.50.50.119
          ansible_python_interpreter: /usr/bin/python3
          k3s_control_node: false     
      vars:
        ansible_user: nprodromou
    rpi4:
      hosts:
        aprp[01-12]:
    rpi3:
      hosts:
        aprp[13-19]:
    rpi:
      children:
        rpi3:
        rpi4:

workstation:
  hosts:
    nprodromou:
      ansible_host: 10.50.1.110
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
    nprodromou01:
      ansible_host: 10.50.1.158
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: false
  vars:
    ansible_user: nprodromou




