---

kubernetes:
  children:
    master:
      hosts:
        apnas01:
          ansible_host: 10.50.50.10
        apk8s00:
          ansible_host: 10.50.50.40
        apk8s01:
          ansible_host: 10.50.50.41
        apk8s02:
          ansible_host: 10.50.50.42
        aprp01:
          ansible_host: 10.50.50.101
      vars:
        ansible_user: nprodromou
    worker:
      hosts:
        aprp02:
          ansible_host: 10.50.50.102
          rook_devices:
          - /dev/sda1
        aprp03:
          ansible_host: 10.50.50.103
        aprp04:
          ansible_host: 10.50.50.104
          rook_devices:
          - /dev/sda1
        aprp05:
          ansible_host: 10.50.50.105
        aprp06:
          ansible_host: 10.50.50.106
          rook_devices:
          - /dev/sda1
        aprp07:
          ansible_host: 10.50.50.107
        aprp08:
          ansible_host: 10.50.50.108
          rook_devices:
          - /dev/sda1
        aprp09:
          ansible_host: 10.50.50.109
        aprp10:
          ansible_host: 10.50.50.110
          rook_devices:
          - /dev/sda1
        aprp11:
          ansible_host: 10.50.50.111
        aprp12:
          ansible_host: 10.50.50.112
          rook_devices:
          - /dev/sda1
        aprp13:
          ansible_host: 10.50.50.113
        aprp14:
          ansible_host: 10.50.50.114
        aprp15:
          ansible_host: 10.50.50.115
        aprp16:
          ansible_host: 10.50.50.116
        # aprp17:
        #   ansible_host: 10.50.50.117
        # aprp18:
        #   ansible_host: 10.50.50.118
        # aprp19:
        #   ansible_host: 10.50.50.119     
      vars:
        ansible_user: nprodromou

workstation:
  hosts:
    nprodromou:
      ansible_host: 10.50.1.110
    nprodromou01:
      ansible_host: 10.50.1.158

